### ISSUE TITLE
To-DO (Create the README.md template)

### ISSUE THREAD

**Issue by Idjjurado** [Idjjurado/SUPER-TEAM-PROJECT-8#5]
# Summary
I will be creating the README template so that we have it readily available 

# TASKS
_Make sure we have the complete template._
_What the README will include:_
- [ ] TITLE
- [ ] Link: ( URL for deployed page)
   - [ ] Include screenshot for deployed page here
- [ ] USAGE
- [ ] CREDIT/COLLABORATORS
- [ ] LICENSE
- [ ] ACCEPTANCE CRITERIA (With screenshots if applicable)
